### ISSUE TITLE
Several URLs open 404s

### ISSUE THREAD

**Issue by lwhinson** [ibm-cloud-architecture/refarch-kc#121]
The following URLs open 404s:

- https://ibm-cloud-architecture.github.io/refarch-kc/analysis/readme/
- https://ibm-cloud-architecture.github.io/refarch-kc/deployments/reposlist/
- https://ibm-cloud-architecture.github.io/refarch-kc/itg-tests/dlq/dlq/
- https://ibm-cloud-architecture.github.io/refarch-kc/itg-tests/saga/saga/
- https://ibm-cloud-architecture.github.io/refarch-kc/itg-tests/happy-path/happy_path/

As a result, several pages in the IBM Cloud Architecture Center now contain broken links, which our tests our flagging. Please let me know whether replacement URLs exist for those pages or if I should remove our references to them. Thanks.

**Comment by osowski** [comment]
In order, due to refactoring of the solution implementation repository, these have been moved to the following URLs:

- https://ibm-cloud-architecture.github.io/refarch-kc/implementation/event-storming-analysis/
- https://ibm-cloud-architecture.github.io/refarch-kc/business-scenario/repository-overview/
- https://ibm-cloud-architecture.github.io/refarch-kc/integration-tests/dead-letter-queue/
- https://ibm-cloud-architecture.github.io/refarch-kc/integration-tests/saga-pattern/
- https://ibm-cloud-architecture.github.io/refarch-kc/integration-tests/happy-path/

Can you point me to your testing that you are running for 404s? I would like to possibly leverage a similar pattern for the two gitbooks we have (and possibly more throughout GSE)

**Comment by lwhinson** [comment]
Thanks @osowski! The tests that I mentioned are run by our infrastructure team. I can ask them what they're using. I'll let you know.

**Comment by lwhinson** [comment]
@osowski I asked one of the members of the infrastructure team, and she said "We have tests that crawl the links on our pages, and for each link found  the test executes a curl request to see if it is available."

**Comment by osowski** [comment]
Excellent. Thank you! I wasn't sure if there was a tool that was available automatically to do that, but we can also manage that with some curl scripts as well.

**Comment by osowski** [comment]
@lwhinson Let me know if you've updated the necessary items in the Architecture Center to reflect the new URLs and I will close this issue.

**Comment by lwhinson** [comment]
@osowski We're all good. Thanks!
