### ISSUE TITLE
Kafka cluster throws error - ErrImagePull 

### ISSUE THREAD

**Issue by jgothan** [ibm-cloud-architecture/refarch-kc#143]
when I run the step 1 command "./kcontainer-quickstart-ocp.sh" from the below link
 https://ibm-cloud-architecture.github.io/refarch-kc/business-scenario/quickstart-tutorial/
The kafka cluster pod is throwing error. 

![image](https://user-images.githubusercontent.com/48895704/105274739-6cca0180-5b63-11eb-8d44-08c3537ba235.png)

**Comment by osowski** [comment]
This is due to the Kafka Cluster not spinning up correctly. In your `oc get pods` command, there are no Kafka pods displayed. You will need to take a look at the Kafka cluster that is deployed in that namespace, as there are a number of reasons why the Kafka cluster itself may not get deployed.

This could be due to an operator deployment or configuration issue, network issues related to pulling the public Kafka container images, or something else related to the OCP cluster. Check that out by running an `oc describe kafka.kafka.strimzi.io my-cluster -n shipping` , as well as inspecting the Operators that are installed on the *Installed Operators* page of the OCP console for the `shipping` namespace.

**Comment by osowski** [comment]
Based on some instability introduced into the Strimzi operator's "stable" stream, I've switched the quickstart script to using the last verified functioning version (0.20.x) and not the generic "stable". Rerun your deployment and give it a shot on a clean cluster (or one that has been verified to have removed the other Strimzi Operator deployments).
